### ISSUE TITLE
Querying: tags bracket is completely ignored

### ISSUE THREAD

**Issue by joeltjarnstig** [hi3g/freki#127]
It seems the "tags" part of a query is completely ignored since the two following queries return the exact same data
<code>SELECT sys.cpu{host=ironman} BETWEEN 1 AND 50000;</code>
<code>SELECT sys.cpu BETWEEN 1 AND 50000;</code>
It is even possible to put anything within the tags brackets:
<code>SELECT sys.cpu{"anything goes"} BETWEEN 1 AND 50000;</code>

**Comment by Kasidro** [comment]
fixed in #136
