### ISSUE TITLE
Exception thrown when publishing new ID through the event bus

### ISSUE THREAD

**Issue by joeltjarnstig** [hi3g/freki#63]
When attempting to add labels via the HTTP API the following happens:

```
2015-07-20 16:02:14,474 INFO  [cluster1-nio-worker-1] LabelClientTypeContext: Completed pending assignment for: test
Jul 20, 2015 4:05:37 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
SEVERE: Could not dispatch event: se.tre.freki.search.IdChangeIndexerListener@740abb5 to public final void se.tre.freki.search.IdChangeIndexerListener.recordLabelCreated(se.tre.freki.labels.LabelCreatedEvent)
```

**Comment by joeltjarnstig** [comment]
The exception is thrown in the CassandraStore class at:
<code>
  public ListenableFuture<LabelMeta> getMeta(final LabelId uid,
                                             final LabelType type) {
    throw new UnsupportedOperationException("Not implemented yet");
  }
</code>
Implementing this method would probably fix this issue

**Comment by jzeeck** [comment]
This is connected to #72. We currently do not create meta objects thus we do not fetch either. The solution we agreed upon is to create such meta for each LabelId and LabelType at the creation of a label.

**Comment by jzeeck** [comment]
See #88

**Comment by luuse** [comment]
This problem is solved now but there a new similar issue now though. See #105.
